
redis:
  host: 127.0.0.1
  port: 6379
  db: 0


mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password:
  dbname: test
  charset: utf8mb4
  timeout: 10


logger:
  filepath: storage/logs
  filename: logger.log